services:
  - type: web
    name: track-way
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: ADMIN_EMAIL
        value: saacsoftwares@gmail.com
      - key: ADMIN_PASSWORD
        value: jqpaxkybakpiolcq